application:
  title: Catalog - seller catalog
  version: 0.0.1-SNAPSHOT

environment: ${ENVIRONMENT:local}

server:
  port: 0

spring:
  application:
    name: catalog-ms
  datasource:
    url: jdbc:postgresql://${SQL_DATABASE_SERVER_HOST:localhost}:${SQL_DATABASE_SERVER_PORT:5432}/${SQL_DATABASE_NAME:erp}?currentSchema=catalog
    username: ${SQL_DATABASE_USERNAME:monitora}
    password: ${SQL_DATABASE_PASSWORD:monitora}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    flyway:
      enabled: true
      schemas: user
      baseline-on-migrate: true
      baseline-version: "1_001"
      ignore-future-migrations: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}