version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypass
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: always
    # networks:
    #   - postgres

  mysqlsrv:
    container_name: mysql_container
    image: mysql
    command: [
      "--default-authentication-plugin=mysql_native_password",
      "--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    ]
    restart: always
    environment:
      MYSQL_DATABASE: financialworker
      MYSQL_USER: matheus
      MYSQL_PASSWORD: m@th3us
      MYSQL_ROOT_PASSWORD: m@th3us 
    volumes:
      - mysql-data:/var/lib/mysql

# networks:
#   postgres:
#     driver: bridge

volumes:
    postgres:
    mysql-data: