application:
  title: Financial Worker MS - Worker to generate bills
  version: 0.0.1-SNAPSHOT

environment: ${ENVIRONMENT:local}

server:
  port: 0

spring:
  application:
    name: financial-worker
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/financialworker
    username: root
    password: m@th3us
#    driverClassName: mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always

app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/erp?currentSchema=customer
    username: postgres
    password: mypass
#    driverClassName: org.postgresql.Driver

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}
