application:
  title: Financial Worker MS - Worker to generate bills
  version: 0.0.1-SNAPSHOT

environment: ${ENVIRONMENT:local}

server:
  port: 8082

spring:
  application:
    name: financial-worker
  datasource:
    url: jdbc:mysql://localhost:3306/financialworker
    username: root
    password: m@th3us
    driver-class-name=com: mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always
