application:
  title: Gateway
  version: 0.0.1-SNAPSHOT

environment: ${ENVIRONMENT:local}

server:
  port: 8081

spring:
  application:
    name: gateway-ms
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}