application:
  title: Eureka - Discovery Service
  version: ${VERSION:0.0.1-SNAPSHOT}

environment: ${ENVIRONMENT:local}

spring:
  application:
    name: eureka

server:
  port: 8761

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: false